dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.0
  - OpenZeppelin/openzeppelin-contracts@4.8.0

compiler:
  solc:
    remappings:
      - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0"
